version: "3"

services:
  prerender:
    restart: always
    build:
      context: ./node/
      dockerfile: Dockerfile
    container_name: prerender
    cap_add:
      - SYS_ADMIN
    networks:
      blognetwork:
        ipv4_address: 172.19.0.13
    ports:
      - "8888:8888"
    depends_on:
      - webapp
      - nginx
    environment:
      - NODE_ENV=production
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_blog
    restart: always
    depends_on:
      - database
    networks:
      blognetwork:
        ipv4_address: 172.19.0.11
    ports:
      - "8000:8000"
    command: gunicorn -c gunicorn.conf.py --preload app.main:app
    volumes:
      - $HOME/blog_image:/files
      - $HOME/logs:/logs/web/
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: ""
      SERVER_NAME: "127.0.0.1"
      SECRET_KEY: ""
      JWT_SECRET_KEY: ""
      SENTRY_DSN: ""
      MAIL_PASSWORD: ""
      MAIL_USERNAME: ""
      API_SECURITY_STRING: ""
      MYSQL_ADDRESS: "172.19.0.10:3306"
      UPLOAD_FOLDER: "/files"
      FLASK_ENV: "production"
      LOG_DIR: "/logs/web/"
      LOG_LEVEL: 'error' # gunicorn 日志等级
  nginx:
    restart: always
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    networks:
      blognetwork:
        ipv4_address: 172.19.0.12
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - webapp
    volumes:
      - /data/certs/:/etc/nginx/certs
      - $HOME/blog_image:/static/images/
      - $HOME/logs/nginx/:/var/log/nginx/
      - /etc/localtime:/etc/localtime
  database:
    build:
      context: ./mysql/
      dockerfile: Dockerfile
    container_name: mysql
    volumes:
      - $HOME/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3306:3306"
    networks:
      blognetwork:
        ipv4_address: 172.19.0.10
networks:
  blognetwork:
    ipam:
      config:
        - subnet: 172.19.0.0/16

