"""添加avatar 字段

Revision ID: 0424a7a441df
Revises: d7bc6a37a142
Create Date: 2020-07-17 13:06:01.601198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0424a7a441df'
down_revision = 'd7bc6a37a142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('avatar', sa.String(length=256), nullable=True, comment='头像'))
    op.alter_column('comment', 'show',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_comment='评论是否显示/用于审核',
               existing_nullable=True)
    op.add_column('comment_reply', sa.Column('avatar', sa.String(length=256), nullable=True, comment='头像'))
    op.alter_column('comment_reply', 'show',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_comment='评论是否显示/用于审核',
               existing_nullable=True)
    op.alter_column('post', 'isRichText',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_comment='摘录是否为富文本',
               existing_nullable=True)
    op.alter_column('user', 'email_is_validate',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email_is_validate',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('post', 'isRichText',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_comment='摘录是否为富文本',
               existing_nullable=True)
    op.alter_column('comment_reply', 'show',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_comment='评论是否显示/用于审核',
               existing_nullable=True)
    op.drop_column('comment_reply', 'avatar')
    op.alter_column('comment', 'show',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_comment='评论是否显示/用于审核',
               existing_nullable=True)
    op.drop_column('comment', 'avatar')
    # ### end Alembic commands ###
