"""添加show 字段

Revision ID: 1c244ec2eb32
Revises: 72b22b03a5f7
Create Date: 2020-07-07 20:08:27.309622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c244ec2eb32'
down_revision = '72b22b03a5f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('show', sa.Boolean(), nullable=True, comment='评论是否显示/用于审核'))
    op.add_column('comment_replay', sa.Column('show', sa.Boolean(), nullable=True, comment='评论是否显示/用于审核'))
    op.alter_column('post', 'isRichText',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_comment='摘录是否为富文本',
               existing_nullable=True)
    op.alter_column('user', 'email_is_validate',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email_is_validate',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('post', 'isRichText',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_comment='摘录是否为富文本',
               existing_nullable=True)
    op.drop_column('comment_replay', 'show')
    op.drop_column('comment', 'show')
    # ### end Alembic commands ###
