"""添加excerpt_hmlt ,article_html about_html 字段

Revision ID: 21edc6722869
Revises: 
Create Date: 2020-04-09 21:25:03.322107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21edc6722869'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('article_html', mysql.LONGTEXT(), nullable=True, comment='文章内容(html)'))
    op.add_column('post', sa.Column('excerpt_html', sa.TEXT(), nullable=True, comment='文章摘要(html)'))
    op.alter_column('post', 'article',
               existing_type=mysql.LONGTEXT(),
               comment='文章内容(json)',
               existing_comment='文章内容',
               existing_nullable=True)
    op.alter_column('post', 'excerpt',
               existing_type=mysql.TEXT(),
               comment='文章摘要(json)',
               existing_comment='文章摘要',
               existing_nullable=True)
    op.add_column('user', sa.Column('about_html', mysql.LONGTEXT(), nullable=True, comment='关于用户(html)'))
    op.alter_column('user', 'about',
               existing_type=mysql.LONGTEXT(),
               comment='关于用户(json raw)',
               existing_comment='关于用户',
               existing_nullable=True)
    op.alter_column('user', 'email_is_validate',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email_is_validate',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('user', 'about',
               existing_type=mysql.LONGTEXT(),
               comment='关于用户',
               existing_comment='关于用户(json raw)',
               existing_nullable=True)
    op.drop_column('user', 'about_html')
    op.alter_column('post', 'excerpt',
               existing_type=mysql.TEXT(),
               comment='文章摘要',
               existing_comment='文章摘要(json)',
               existing_nullable=True)
    op.alter_column('post', 'article',
               existing_type=mysql.LONGTEXT(),
               comment='文章内容',
               existing_comment='文章内容(json)',
               existing_nullable=True)
    op.drop_column('post', 'excerpt_html')
    op.drop_column('post', 'article_html')
    # ### end Alembic commands ###
