"""post 模型添加isRichText字段

Revision ID: 22f04a219e57
Revises: 6bc3bca0838b
Create Date: 2020-07-07 14:36:27.076181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22f04a219e57'
down_revision = '6bc3bca0838b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('isRichText', sa.Boolean(), nullable=True, comment='摘录是否为富文本'))
    op.alter_column('user', 'email_is_validate',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email_is_validate',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('post', 'isRichText')
    # ### end Alembic commands ###
