"""添加content字段 string(255)-> text

Revision ID: 2b1aa741d4be
Revises: 0424a7a441df
Create Date: 2020-07-17 13:18:53.319586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b1aa741d4be'
down_revision = '0424a7a441df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'show',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_comment='评论是否显示/用于审核',
                    existing_nullable=True)
    op.alter_column('comment_reply', 'show',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_comment='评论是否显示/用于审核',
                    existing_nullable=True)
    op.alter_column('post', 'isRichText',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_comment='摘录是否为富文本',
                    existing_nullable=True)
    op.alter_column('user', 'email_is_validate',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=True)

    op.alter_column('comment', 'content',
                    existing_type=sa.String(255),
                    type_=sa.TEXT,
                    existing_comment="评论内容",
                    existing_nullable=True)
    op.alter_column('comment_reply', 'content',
                    existing_type=sa.String(255),
                    type_=sa.TEXT,
                    existing_comment='评论内容',
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email_is_validate',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=True)
    op.alter_column('post', 'isRichText',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_comment='摘录是否为富文本',
                    existing_nullable=True)
    op.alter_column('comment_reply', 'show',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_comment='评论是否显示/用于审核',
                    existing_nullable=True)
    op.alter_column('comment', 'show',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_comment='评论是否显示/用于审核',
                    existing_nullable=True)

    op.alter_column('comment', 'content',
                    existing_type=sa.TEXT,
                    type_=sa.String(255),
                    existing_comment="评论内容",
                    existing_nullable=True)
    op.alter_column('comment_reply', 'content',
                    existing_type=sa.TEXT,
                    type_=sa.String(255),
                    existing_comment='评论内容',
                    existing_nullable=True)
    # ### end Alembic commands ###
