"""post 模型添加excerpt_rich_text_html excerpt_rich_text字段

Revision ID: 6bc3bca0838b
Revises: 
Create Date: 2020-07-07 14:30:25.136879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6bc3bca0838b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'excerpt',
               existing_type=mysql.TEXT(),
               comment='文章摘要(普通文本)',
               existing_comment='文章摘要(json)',
               existing_nullable=True)
    op.drop_column('post', 'excerpt_html')
    op.alter_column('user', 'email_is_validate',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email_is_validate',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.add_column('post', sa.Column('excerpt_html', mysql.TEXT(), nullable=True, comment='文章摘要(html)'))
    op.alter_column('post', 'excerpt',
               existing_type=mysql.TEXT(),
               comment='文章摘要(json)',
               existing_comment='文章摘要(普通文本)',
               existing_nullable=True)
    # ### end Alembic commands ###
