"""添加模型:Comment与Blog

Revision ID: 6c127391c736
Revises: f7f87922844f
Create Date: 2020-07-07 17:58:56.318066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c127391c736'
down_revision = 'f7f87922844f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'excerpt',
               existing_type=mysql.VARCHAR(length=300),
               comment='文章摘要(普通文本)',
               existing_nullable=True)
    op.alter_column('post', 'isRichText',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_comment='摘录是否为富文本',
               existing_nullable=True)
    op.alter_column('user', 'email_is_validate',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email_is_validate',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('post', 'isRichText',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_comment='摘录是否为富文本',
               existing_nullable=True)
    op.alter_column('post', 'excerpt',
               existing_type=mysql.VARCHAR(length=300),
               comment=None,
               existing_comment='文章摘要(普通文本)',
               existing_nullable=True)
    # ### end Alembic commands ###
