"""添加CommentReplay模型

Revision ID: 72b22b03a5f7
Revises: 6c127391c736
Create Date: 2020-07-07 20:01:55.851850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72b22b03a5f7'
down_revision = '6c127391c736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'parent_id')
    op.alter_column('post', 'isRichText',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_comment='摘录是否为富文本',
               existing_nullable=True)
    op.alter_column('user', 'email_is_validate',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email_is_validate',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('post', 'isRichText',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_comment='摘录是否为富文本',
               existing_nullable=True)
    op.add_column('comment', sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='父评论id,父评论为文章则显示-1'))
    # ### end Alembic commands ###
