"""合并comment/commentReply表

Revision ID: c9b1c5e80573
Revises: 2b1aa741d4be
Create Date: 2020-07-22 21:01:21.150805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9b1c5e80573'
down_revision = '2b1aa741d4be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('parent_id', sa.Integer(), nullable=True, comment='父回复id'))
    op.alter_column('comment', 'post_id',
               existing_type=mysql.INTEGER(),
               comment='文章id',
               existing_nullable=True)
    op.alter_column('comment', 'show',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_comment='评论是否显示/用于审核',
               existing_nullable=True)
    op.alter_column('post', 'isRichText',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_comment='摘录是否为富文本',
               existing_nullable=True)
    op.alter_column('user', 'email_is_validate',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email_is_validate',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('post', 'isRichText',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_comment='摘录是否为富文本',
               existing_nullable=True)
    op.alter_column('comment', 'show',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_comment='评论是否显示/用于审核',
               existing_nullable=True)
    op.alter_column('comment', 'post_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='文章id',
               existing_nullable=True)
    op.drop_column('comment', 'parent_id')
    # ### end Alembic commands ###
