"""重构

Revision ID: cccceb492a87
Revises: 8e6b438b6def
Create Date: 2020-02-14 15:36:17.166759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cccceb492a87'
down_revision = '8e6b438b6def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'article',
               existing_type=mysql.LONGTEXT(),
               comment='文章内容',
               existing_nullable=True)
    op.alter_column('post', 'comments',
               existing_type=mysql.INTEGER(),
               comment='评论数量',
               existing_nullable=True)
    op.alter_column('post', 'visibility',
               existing_type=mysql.VARCHAR(length=16),
               comment='文章可见性:私密/公开',
               existing_nullable=True)
    op.add_column('user', sa.Column('about', mysql.LONGTEXT(), nullable=True, comment='关于用户'))
    op.alter_column('user', 'email_is_validate',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_column('user', 'phone_is_validate')
    op.drop_column('user', 'user_about')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('user', sa.Column('user_about', mysql.LONGTEXT(), nullable=True))
    op.add_column('user', sa.Column('phone_is_validate', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.alter_column('user', 'is_active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('user', 'email_is_validate',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('user', 'about')
    op.alter_column('post', 'visibility',
               existing_type=mysql.VARCHAR(length=16),
               comment=None,
               existing_comment='文章可见性:私密/公开',
               existing_nullable=True)
    op.alter_column('post', 'comments',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='评论数量',
               existing_nullable=True)
    op.alter_column('post', 'article',
               existing_type=mysql.LONGTEXT(),
               comment=None,
               existing_comment='文章内容',
               existing_nullable=True)
    # ### end Alembic commands ###
