"""添加chnage_date 字段

Revision ID: d7bc6a37a142
Revises: 1c244ec2eb32
Create Date: 2020-07-11 16:30:46.325475

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7bc6a37a142'
down_revision = '1c244ec2eb32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('change_date', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_blog_change_date'), 'blog', ['change_date'], unique=False)
    op.alter_column('comment', 'show',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_comment='评论是否显示/用于审核',
               existing_nullable=True)
    op.drop_constraint('comment_ibfk_1', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.alter_column('comment_reply', 'comment_id',
               existing_type=mysql.INTEGER(),
               comment='文章评论的回复id',
               existing_comment='文章评论回复id',
               existing_nullable=True)
    op.alter_column('comment_reply', 'show',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_comment='评论是否显示/用于审核',
               existing_nullable=True)
    op.create_index(op.f('ix_comment_reply_create_date'), 'comment_reply', ['create_date'], unique=False)
    op.drop_index('ix_comment_replay_create_date', table_name='comment_reply')
    op.drop_constraint('comment_reply_ibfk_1', 'comment_reply', type_='foreignkey')
    op.create_foreign_key(None, 'comment_reply', 'comment', ['comment_id'], ['id'], ondelete='CASCADE')
    op.alter_column('post', 'isRichText',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_comment='摘录是否为富文本',
               existing_nullable=True)
    op.alter_column('user', 'email_is_validate',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email_is_validate',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('post', 'isRichText',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_comment='摘录是否为富文本',
               existing_nullable=True)
    op.drop_constraint(None, 'comment_reply', type_='foreignkey')
    op.create_foreign_key('comment_reply_ibfk_1', 'comment_reply', 'comment', ['comment_id'], ['id'])
    op.create_index('ix_comment_replay_create_date', 'comment_reply', ['create_date'], unique=False)
    op.drop_index(op.f('ix_comment_reply_create_date'), table_name='comment_reply')
    op.alter_column('comment_reply', 'show',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_comment='评论是否显示/用于审核',
               existing_nullable=True)
    op.alter_column('comment_reply', 'comment_id',
               existing_type=mysql.INTEGER(),
               comment='文章评论回复id',
               existing_comment='文章评论的回复id',
               existing_nullable=True)
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_1', 'comment', 'post', ['post_id'], ['id'])
    op.alter_column('comment', 'show',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_comment='评论是否显示/用于审核',
               existing_nullable=True)
    op.drop_index(op.f('ix_blog_change_date'), table_name='blog')
    op.drop_column('blog', 'change_date')
    # ### end Alembic commands ###
