"""添加Post 与Link关系

Revision ID: e3c8123a7d21
Revises: 22f04a219e57
Create Date: 2020-07-07 14:48:55.473961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3c8123a7d21'
down_revision = '22f04a219e57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('illustration_id', sa.Integer(), nullable=True, comment='插图链接id'))
    op.alter_column('post', 'excerpt',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=300),
               existing_comment='文章摘要(普通文本)',
               existing_nullable=True)
    op.alter_column('post', 'isRichText',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_comment='摘录是否为富文本',
               existing_nullable=True)
    op.create_foreign_key(None, 'post', 'link', ['illustration_id'], ['id'])
    op.alter_column('user', 'email_is_validate',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email_is_validate',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.alter_column('post', 'isRichText',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_comment='摘录是否为富文本',
               existing_nullable=True)
    op.alter_column('post', 'excerpt',
               existing_type=sa.String(length=300),
               type_=mysql.TEXT(),
               existing_comment='文章摘要(普通文本)',
               existing_nullable=True)
    op.drop_column('post', 'illustration_id')
    # ### end Alembic commands ###
