"""修改Post.excerpt 字段类型 TEXT-> string(300)

Revision ID: f7f87922844f
Revises: e3c8123a7d21
Create Date: 2020-07-07 14:51:01.489413

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7f87922844f'
down_revision = 'e3c8123a7d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'isRichText',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_comment='摘录是否为富文本',
                    existing_nullable=True)
    op.alter_column('user', 'email_is_validate',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=True)
    op.alter_column('post', 'excerpt',
                    existing_type=sa.TEXT,
                    type_=sa.String(300),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email_is_validate',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=True)
    op.alter_column('post', 'excerpt',
                    existing_type=sa.String(300),
                    type_=sa.TEXT,
                    existing_nullable=True)
    op.alter_column('post', 'isRichText',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_comment='摘录是否为富文本',
                    existing_nullable=True)
    # ### end Alembic commands ###
